# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: zoo3
  path.config: "pipeline/zoo3.conf"
- pipeline.id: bookie3
  path.config: "pipeline/bookie3.conf"
- pipeline.id: broker3
  path.config: "pipeline/broker3.conf"
#- pipeline.id: cass3
#  path.config: "pipeline/cass3.conf"
