{
 "title": "Bookies",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum by (instance) (irate(process_cpu_seconds_total{job=\"bookies\"}[1m])) / 60 ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{job=\"bookies\", area=\"heap\"} / jvm_memory_bytes_max{job=\"bookies\", area=\"heap\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(process_cpu_seconds_total{job=\"bookies\"}[1m])) / 60 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"bookies\", area=\"heap\"} / 1048576",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"bookies\", area=\"heap\"} / 1048576",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  }
 ]
}