{
 "title": "Brokers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Subscriber Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pulsar_subscriptions_count", "legendFormat": "{{instance}}:{{cluster}}" }
   ]
  },
  {
   "title": "Cluster Topic Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pulsar_topics_count", "legendFormat": "{{instance}}:{{cluster}}" }
   ]
  },
  {
   "title": "Cluster I/O",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pulsar_storage_read_rate", "legendFormat": "r: {{instance}}:{{cluster}}" },
    { "expr": "pulsar_storage_read_rate", "legendFormat": "w: {{instance}}:{{cluster}}" }
   ]
  },
  {
   "title": "Cluster Producer Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "pulsar_producers_count", "legendFormat": "{{instance}}:{{cluster}}" }
   ]
  },
  {
   "title": "Heap Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"brokers\", area=\"heap\"} / 1048576",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"brokers\", area=\"heap\"} / 1048576",
     "legendFormat": "cmmt: {{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"brokers\"}",
     "legendFormat": "{{instance}}:{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(process_cpu_seconds_total{job=\"brokers\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{job=\"brokers\", area=\"heap\"} / jvm_memory_bytes_max{job=\"brokers\", area=\"heap\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}