{
 "title": "Casses",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum by (instance) (irate(process_cpu_seconds_total{job=\"casses\"}[1m])) / 60 ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{job=\"casses\", area=\"heap\"} / jvm_memory_bytes_max{job=\"casses\", area=\"heap\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(process_cpu_seconds_total{job=\"casses\"}[1m])) / 60 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"casses\", area=\"heap\"} / 1048576",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"casses\", area=\"heap\"} / 1048576",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_seconds_count{clientrequest=\"Read-ONE\"}",
     "legendFormat": "client R1 {{instance}}"
    },
    {
     "expr": "cassandra_clientrequest_latency_seconds_count{clientrequest=\"Write-LOCAL_QUORUM\"}",
     "legendFormat": "client WLQ {{instance}}"
    }
   ]
  }
 ]
}