{
 "title": "Dockers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "docker0 Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (name) (irate(container_fs_reads_bytes_total{job=\"dockers\", instance=\"ops.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "r: {{name}}"
    },
    {
     "expr": "(sum by (name) (irate(container_fs_writes_bytes_total{job=\"dockers\", instance=\"ops.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "w: {{name}}"
    }
   ]
  },
  {
   "title": "docker1 Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (name) (irate(container_fs_reads_bytes_total{job=\"dockers\", instance=\"stack1.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "r: {{name}}"
    },
    {
     "expr": "(sum by (name) (irate(container_fs_writes_bytes_total{job=\"dockers\", instance=\"stack1.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "w: {{name}}"
    }
   ]
  },
  {
   "title": "docker2 Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (name) (irate(container_fs_reads_bytes_total{job=\"dockers\", instance=\"stack2.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "r: {{name}}"
    },
    {
     "expr": "(sum by (name) (irate(container_fs_writes_bytes_total{job=\"dockers\", instance=\"stack2.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "w: {{name}}"
    }
   ]
  },
  {
   "title": "docker3 Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (name) (irate(container_fs_reads_bytes_total{job=\"dockers\", instance=\"stack3.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "r: {{name}}"
    },
    {
     "expr": "(sum by (name) (irate(container_fs_writes_bytes_total{job=\"dockers\", instance=\"stack2.cluster.test:9092\", name=~\".+\"}[1m]))) / 1024 / 60",
     "legendFormat": "w: {{name}}"
    }
   ]
  },
  {
   "title": "docker0 Mem Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"ops.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{id=~\"/docker.+\", job=\"dockers\", instance=\"ops.cluster.test:9092\", name=~\".*\"} / 1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "docker1 Mem Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack1.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{id=~\"/docker.+\", job=\"dockers\", instance=\"stack1.cluster.test:9092\", name=~\".*\"} / 1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "docker2 Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack2.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{id=~\"/docker.+\", job=\"dockers\", instance=\"stack2.cluster.test:9092\", name=~\".+\"} / 1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "docker3 Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack3.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{id=~\"/docker.+\", job=\"dockers\", instance=\"stack3.cluster.test:9092\", name=~\".*\"} / 1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(container_cpu_system_seconds_total{id=\"/docker\", job=\"dockers\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((container_memory_usage_bytes{id=\"/docker\", job=\"dockers\"}) / (12*1024*1024*1024) ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}