{
 "title": "Dockers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (irate(container_cpu_system_seconds_total{id=\"/docker\", job=\"dockers\"}[1m])) / 60 ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack1.cluster.test:9092\"}) / (container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack1.cluster.test:9092\"}) * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(container_memory_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack2.cluster.test:9092\"}) / (container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack2.cluster.test:9092\"}) * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(container_memory_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack3.cluster.test:9092\"}) / (container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack3.cluster.test:9092\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "docker1 Mem Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack1.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{job=\"dockers\", id=~\"/docker.+\", instance=\"stack1.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "docker2 Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack2.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{id=~\"/docker.+\", job=\"dockers\", instance=\"stack2.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "docker3 Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{id=\"/docker\", job=\"dockers\", instance=\"stack3.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{id=~\"/docker.+\", job=\"dockers\", instance=\"stack3.cluster.test:9092\"} / 1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "docker1 Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(sum by (name) (irate(container_fs_reads_bytes_total{job=\"dockers\", instance=\"stack1.cluster.test:9092\"}[1m]))) / 1024 / 60",
     "legendFormat": "r: {{name}}"
    },
    {
     "expr": "(sum by (name) (irate(container_fs_writes_bytes_total{job=\"dockers\", instance=\"stack1.cluster.test:9092\"}[1m]))) / 1024 / 60",
     "legendFormat": "w: {{name}}"
    }
   ]
  },
  {
   "title": "docker2 Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "(sum by (name) (irate(container_fs_reads_bytes_total{job=\"dockers\", instance=\"stack2.cluster.test:9092\"}[1m]))) / 1024 / 60",
     "legendFormat": "r: {{name}}"
    },
    {
     "expr": "(sum by (name) (irate(container_fs_writes_bytes_total{job=\"dockers\", instance=\"stack2.cluster.test:9092\"}[1m]))) / 1024 / 60",
     "legendFormat": "w: {{name}}"
    }
   ]
  },
  {
   "title": "docker3 Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "(sum by (name) (irate(container_fs_reads_bytes_total{job=\"dockers\", instance=\"stack3.cluster.test:9092\"}[1m]))) / 1024 / 60",
     "legendFormat": "r: {{name}}"
    },
    {
     "expr": "(sum by (name) (irate(container_fs_writes_bytes_total{job=\"dockers\", instance=\"stack2.cluster.test:9092\"}[1m]))) / 1024 / 60",
     "legendFormat": "w: {{name}}"
    }
   ]
  }
 ]
}