{
 "title": "Stashes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": " Events Pipeline In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance, pipeline) (logstash_pipeline_plugins_filters_events_in{name=\"grok\"})",
     "legendFormat": "{{instance}}-{{pipeline}}"
    }
   ]
  },
  {
   "title": "Event Pipeline Time (msec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance, pipeline)(logstash_pipeline_events_duration_in_millis)   ",
     "legendFormat": "{{instance}}-{{pipeline}}"
    }
   ]
  },
  {
   "title": "Events Elasticsearch Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance, pipeline) (logstash_pipeline_plugins_outputs_events_in{name=\"elasticsearch\"})",
     "legendFormat": "{{instance}}-{{pipeline}}"
    }
   ]
  },
  {
   "title": "Event Output Time (msec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance, pipeline) (logstash_pipeline_plugins_outputs_events_duration_in_millis{name=\"elasticsearch\"})",
     "legendFormat": "{{instance}}-{{pipeline}}"
    }
   ]
  }
 ]
}