{
 "title": "VMs",
 "description": "Virtual Machine OS Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Time  (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance) (irate(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum by (instance) (irate(node_cpu_seconds_total{mode=\"user\"}[1m]))) * 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_memory_MemAvailable_bytes[1m])) / 1048576",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{device=~\"dm-.\"}[1m])) / 1024 / 60",
     "legendFormat": "r: {{instance}}"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_written_bytes_total{device=~\"dm-.\"}[1m])) / 1024 / 60  ",
     "legendFormat": "w: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_memory_Committed_AS_bytes[1m])) / 1048576",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{device=\"enp0s3\"}[1m]) )/ 1024",
     "legendFormat": "r: {{instance}}"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{device=\"enp0s3\"}[1m])) / 1024 ",
     "legendFormat": "w: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes -node_memory_MemFree_bytes) / (1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum by (instance) (irate(node_cpu_seconds_total{mode=\"system\"}[1m])) + sum by (instance) (irate(node_cpu_seconds_total{mode=\"user\"}[1m])) ) * 100\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory % Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes -node_memory_MemFree_bytes ) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}